#!/usr/bin/env bash

# Japanese TV Content Generator (JTV Gen) Script - Simple amatsukaze compatible version
# Generates Japanese TV broadcast dummy files

set -euxo pipefail

INTERVAL=29
VIDEO_OPT="-minrate 1M -b:v 6M -maxrate 12M"

rm -rfv temp/combined.ts final_v1.ts
mkdir -p temp

dump_psi() {
  local filename="${1}"
  local pids=(
    '0x0000,pat'
    '0x0010,nit'
    '0x0011,sdt'
    '0x0012,eit'
    '0x0014,tot'
    '0x0101,pmt'
  )

  mkdir -p temp/psi
  for item in "${pids[@]}"; do
    IFS=',' read -r pid name <<< "$item"
    echo "tstables, PID: $pid, Name: $name"
    tstables --japan --pid $pid --xml-output  "temp/psi/${name}.xml" "$filename"
  done
}
#dump_psi "original_6min.ts"
#exit 1

generate_test_file() {
    local filename="$1"

    if [ ! -f "temp/${filename}" ]; then
        ffmpeg -y -hide_banner \
               -f lavfi -i "testsrc=duration=${INTERVAL}:size=1280x720:rate=30000/1001,format=yuv420p" \
               -f lavfi -i "anullsrc=channel_layout=stereo:sample_rate=48000:duration=0.5" \
               -f lavfi -i "sine=frequency=1000:duration=${INTERVAL}" \
               -f lavfi -i "anullsrc=channel_layout=stereo:sample_rate=48000:duration=0.5" \
               -filter_complex "
                [1:a]volume=-70dB[a_silence1];
                [2:a]volume=-14dB,alimiter=limit=-3dB:attack=5:release=50[a_content];
                [3:a]volume=-70dB[a_silence2];
                [a_silence1][a_content][a_silence2]concat=n=3:v=0:a=1,asetpts=PTS-STARTPTS[a];
                [0:v]setpts=PTS-STARTPTS,fps=30000/1001,format=yuv420p[v]
               " \
               -map "[v]" -map "[a]" \
               -c:v mpeg2video -aspect 16:9 -profile:v main -level:v high \
               ${VIDEO_OPT} \
               -c:a aac -profile:a aac_low -ar 48000 -ac 2 -b:a 248k \
               -fflags +genpts \
               -avoid_negative_ts make_zero \
               -muxdelay 0 -muxpreload 0 \
               "temp/${filename}"
    fi
}

generate_test_file "_stest_1.ts" &
generate_test_file "_stest_2.ts" &
wait

cat > temp/filelist.txt << EOF
file '_stest_1.ts'
file '_stest_2.ts'

EOF

DEFAULT_SERVICE_ID=65024
DEFAULT_TRANSPORT_STREAM_ID=$(( (RANDOM % 65535) + 1 ))
DEFAULT_ORIGINAL_NETWORK_ID=$(( (RANDOM % 65535) + 1 ))
DEFAULT_SERVICE_NAME="JTV Gen"
DEFAULT_SERVICE_PROVIDER="FFmpeg"
DEFAULT_NETWORK_NAME="Generated by naa0yama"
DEFAULT_START_TIME="2024-12-31 15:00:00"
ffmpeg -y -hide_banner \
       -fflags +genpts+igndts \
       -avoid_negative_ts make_zero \
       -f concat -safe 0 -i temp/filelist.txt \
       -c:v copy -c:a copy \
       -mpegts_service_id "${DEFAULT_SERVICE_ID}" \
       -mpegts_transport_stream_id "${DEFAULT_TRANSPORT_STREAM_ID}" \
       -mpegts_start_pid 273 \
       -mpegts_pmt_start_pid 257 \
       -metadata service_provider="${DEFAULT_SERVICE_PROVIDER}" \
       -metadata service_name="${DEFAULT_SERVICE_NAME}" \
       temp/combined.ts
#tsanalyze temp/combined.ts && exit 1

exit 0

#- -----------------------------------------------------------------------------
# Global PID's                          PID       kbps    ms
#   PAT (Program Association Table)  0x0000(  0)  15.0   100 required
#   NIT (Network Information Table)  0x0010( 16)   1.5  1000 receiver
#   SDT (Service Description Table)  0x0011( 17)   0.8  2000 required from ARIB
#   EIT (Event Information Table)    0x0012( 18)  70.0  1000 required from EPG
#   TOT (Time Offset Table)          0x0014( 20)   0.3  5000 Time JST
# Service  PID's
#   PCR                              0x0100(256)
#   PMT (Program Map Table)          0x0101(257)   30.1   100 required
#   MPEG-2 Video                     0x0111(273)    8.83mbps
#   MPEG-2 AAC                       0x0112(274)  248.0
# PAT/NIT/SDT/EIT/TOT/PMT SUM                117.7  (7MB/min)
#
#- Amatsukaze で必要な PSI/SI 情報
# PNSET
# TOT   放送日時
# SDT   チャンネル
# EIT   ジャンル
# PMT   映像サイズ


# シンプルなamatsukaze互換TSファイル生成
echo "Simple amatsukaze compatible TS generation..."

# 最小限のPMT修正のみ実施
cat > temp/pmt.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>
<tsduck>
  <PMT version="1" service_id="${DEFAULT_SERVICE_ID}" PCR_PID="273">
    <component elementary_PID="273" stream_type="0x02">
      <stream_identifier_descriptor component_tag="0"/>
    </component>
    <component elementary_PID="257" stream_type="0x0F">
      <stream_identifier_descriptor component_tag="16"/>
    </component>
  </PMT>
</tsduck>
EOF

# XML→binコンパイル
#echo "Compiling PSI/SI tables..."
#tstabcomp --japan temp/sdt.xml -o temp/sdt.bin
#tstabcomp --japan temp/tot.xml -o temp/tot.bin
#tstabcomp --japan temp/pmt.xml -o temp/pmt.bin

# jtv_gen.sh方式のシンプルなPSI/SI注入
#   PAT (Program Association Table)  0x0000(  0)  15.0   100 required
#   NIT (Network Information Table)  0x0010( 16)   1.5  1000 receiver
#   SDT (Service Description Table)  0x0011( 17)   0.8  2000 required from ARIB
#   EIT (Event Information Table)    0x0012( 18)  70.0  1000 required from EPG
#   TOT (Time Offset Table)          0x0014( 20)   0.3  5000 Time JST
# Service  PID's
#   PCR                              0x0100(256)
#   PMT (Program Map Table)          0x0101(257)   30.1   100 required

# inject
#   NIT 0x0010( 16)
#   EIT 0x0012( 18)
#   TOT 0x0014( 20)
# replace
#   PAT 0x0000(  0)
#   SDT 0x0011( 17)
#   PMT 0x0101(257)
#echo "Injecting basic PSI/SI metadata..."
#tsp --japan -I file temp/combined.ts \
#    -O file final_v1.ts
#tsanalyze final_v1.ts
